### ISSUE TITLE
Can't add children's device

### ISSUE THREAD

**Issue by Elwag** [JordyHers/Times-up-flutter#250] opened 2024-08-11 15:28 UTC
**Describe the bug**
I can't add my child's device because after ~15 seconds it throws an error on the child's device:
"LateInitializationError: Field'_token@1725...' has not been initialized."

**To Reproduce**
1. Setup an account
2. Setup a parent's device, add a child
3. Try to setup the cild's device with the name and given code

**Expected behavior**
The child's device successfully registers and I can configure it.

**Smartphone:**
 - OS: Android
 - Versions: (Child: 13), (Parent: 14)
 

**Screenshots**
![Screenshot_20240811-172200_Time's Up](https://github.com/user-attachments/assets/8424556b-1fb0-4674-ae38-8950ca2c267f)

**Comment by JordyHers** [comment] 2024-08-12 07:40
@Elwag  I have a few questions.

1- Did you mke sure you configured a Parent device before the Child?
2- Did you use the same device to register both.
3- Did you have a valid internet connection?
4- Did you use the same Email/Google account on both devices
5- Did you try from the apk provided or did you run the app locally. If yes, can I see the logs?

**Comment by JordyHers** [comment] 2024-08-26 08:43
Duplicate of #251 Please refer to this thread

**Closed as completed** 2024-08-26 08:43 UTC
